steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/translationweb'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/translationweb'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - translationweb
      - '--image'
      - 'gcr.io/$PROJECT_ID/translationweb'
      - '--region'
      - europe-west1
      - '--platform'
      - managed
    entrypoint: gcloud
timeout: 1200s
images:
  - 'gcr.io/$PROJECT_ID/translationweb'
options:
  logging: CLOUD_LOGGING_ONLY